//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnotherMusicPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnotherMusicPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add_white {
            get {
                object obj = ResourceManager.GetObject("add_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap album_large {
            get {
                object obj = ResourceManager.GetObject("album_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;svg version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;512&quot; height=&quot;512&quot;&gt;
        ///&lt;path d=&quot;M0 0 C0.78177738 -0.00581376 1.56355476 -0.01162753 2.36902237 -0.01761746 C4.99266607 -0.03223318 7.61537655 -0.0183252 10.23901367 -0.00457001 C12.13732889 -0.0091783 14.03564053 -0.01553074 15.9339447 -0.02347898 C21.15362574 -0.04020519 26.37301494 -0.03191092 31.59269714 -0.01953411 C37.22059119 -0.01049944 42.84843436 -0.02444549 48.47631836 -0.0354538 C59.5026231 -0.0532605  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string album_svg {
            get {
                return ResourceManager.GetString("album_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CoverImg {
            get {
                object obj = ResourceManager.GetObject("CoverImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dialog_error {
            get {
                object obj = ResourceManager.GetObject("dialog_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dialog_info {
            get {
                object obj = ResourceManager.GetObject("dialog_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dialog_warning {
            get {
                object obj = ResourceManager.GetObject("dialog_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dot {
            get {
                object obj = ResourceManager.GetObject("dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_open_icon_white {
            get {
                object obj = ResourceManager.GetObject("folder_open_icon_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Grip_transparent {
            get {
                object obj = ResourceManager.GetObject("Grip_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon icon_large {
            get {
                object obj = ResourceManager.GetObject("icon_large", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap next_24 {
            get {
                object obj = ResourceManager.GetObject("next_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pause_24 {
            get {
                object obj = ResourceManager.GetObject("pause_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_24 {
            get {
                object obj = ResourceManager.GetObject("play_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap previous_24 {
            get {
                object obj = ResourceManager.GetObject("previous_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap radio_icon {
            get {
                object obj = ResourceManager.GetObject("radio_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star_color {
            get {
                object obj = ResourceManager.GetObject("star_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star_gray {
            get {
                object obj = ResourceManager.GetObject("star_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_0_0 {
            get {
                object obj = ResourceManager.GetObject("stars_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_0_5 {
            get {
                object obj = ResourceManager.GetObject("stars_0_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_1_0 {
            get {
                object obj = ResourceManager.GetObject("stars_1_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_1_5 {
            get {
                object obj = ResourceManager.GetObject("stars_1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_2_0 {
            get {
                object obj = ResourceManager.GetObject("stars_2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_2_5 {
            get {
                object obj = ResourceManager.GetObject("stars_2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_3_0 {
            get {
                object obj = ResourceManager.GetObject("stars_3_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_3_5 {
            get {
                object obj = ResourceManager.GetObject("stars_3_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_4_0 {
            get {
                object obj = ResourceManager.GetObject("stars_4_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_4_5 {
            get {
                object obj = ResourceManager.GetObject("stars_4_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stars_5_0 {
            get {
                object obj = ResourceManager.GetObject("stars_5_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ResourceDictionary&gt;
        ///
        ///    &lt;!--#region Files sizes--&gt;
        ///    &lt;SizeBytesUnit&gt;&lt;![CDATA[B]]&gt;&lt;/SizeBytesUnit&gt;
        ///    &lt;SizeBytesKilo&gt;&lt;![CDATA[Kib]]&gt;&lt;/SizeBytesKilo&gt;
        ///    &lt;SizeBytesMega&gt;&lt;![CDATA[Mib]]&gt;&lt;/SizeBytesMega&gt;
        ///    &lt;SizeBytesGiga&gt;&lt;![CDATA[Gib]]&gt;&lt;/SizeBytesGiga&gt;
        ///    &lt;SizeBytesTera&gt;&lt;![CDATA[Tib]]&gt;&lt;/SizeBytesTera&gt;
        ///    &lt;SizeBytesPeta&gt;&lt;![CDATA[Pib]]&gt;&lt;/SizeBytesPeta&gt;
        ///    &lt;SizeBytesExa&gt;&lt;![CDATA[Eib]]&gt;&lt;/SizeBytesExa&gt;
        ///    &lt;!--#endregion--&gt;
        ///
        ///    &lt;!--#region Base Window --&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Translation_English {
            get {
                return ResourceManager.GetString("Translation_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ResourceDictionary&gt;
        ///
        ///    &lt;!--#region Files sizes--&gt;
        ///    &lt;SizeBytesUnit&gt;&lt;![CDATA[B]]&gt;&lt;/SizeBytesUnit&gt;
        ///    &lt;SizeBytesKilo&gt;&lt;![CDATA[Kib]]&gt;&lt;/SizeBytesKilo&gt;
        ///    &lt;SizeBytesMega&gt;&lt;![CDATA[Mib]]&gt;&lt;/SizeBytesMega&gt;
        ///    &lt;SizeBytesGiga&gt;&lt;![CDATA[Gib]]&gt;&lt;/SizeBytesGiga&gt;
        ///    &lt;SizeBytesTera&gt;&lt;![CDATA[Tib]]&gt;&lt;/SizeBytesTera&gt;
        ///    &lt;SizeBytesPeta&gt;&lt;![CDATA[Pib]]&gt;&lt;/SizeBytesPeta&gt;
        ///    &lt;SizeBytesExa&gt;&lt;![CDATA[Eib]]&gt;&lt;/SizeBytesExa&gt;
        ///    &lt;!--#endregion--&gt;
        ///
        ///    &lt;!--#region Base Window --&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Translation_Français {
            get {
                return ResourceManager.GetString("Translation_Français", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap window_close_icon {
            get {
                object obj = ResourceManager.GetObject("window_close_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap window_maximize_icon {
            get {
                object obj = ResourceManager.GetObject("window_maximize_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap window_minimize_icon {
            get {
                object obj = ResourceManager.GetObject("window_minimize_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
